version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13-browsers # the primary container, where your job's commands are run
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-build
          command: yarn ng build --prod --aot --no-progress
#      - run:
#          name: angular-test
#          command: yarn run test
#      - store_artifacts:
#          path: test-results.xml
#          prefix: tests
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://github.com/rostyslavnikitin/playsoundsqueue.git production

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
